### PR TITLE
New deforest() function for removing trees from a fitted random forest

### PR DESCRIPTION
**Pull request by bgreenwell**
Hi @mnwright,

This PR addresses  issue [(#568)](https://github.com/imbs-hl/ranger/issues/568), and contains the following changes:

* New file `R/deforest.R` containing the new `deforest() function with full documentation, examples, and relevant links.
* New file `tests/testthat/ranger_deforest.R` for testing the expected output of `deforest()`. (Survival forests are the only tree type not currently supported.)
* New file `R/print.deforest.ranger.R` containing a modified version of `print.ranger()` with full documentation.

Please let me know if I missed something or you notice any issues.

Best,

Brandon G.

### CODE REVIEW

**Comment by bgreenwell** [comment]
Looks like I didn’t catch the missing documentation for one of the arguments. Will push an update shortly.

**Review by mnwright — COMMENTED** [review]
The .dll file should not be in the PR.

**Comment by bgreenwell** [comment]
Added support for survival forests, updated tests, and removed the `.dll`.

**Comment by mnwright** [comment]
Thanks, merged (finally!).

**Pull request merged**
