### PR TITLE
MIT-only changes from master (2020-03-13)

### LINKED ISSUE #538: Could not open input file. Too few columns in row 0. Are all values numeric?
Hi  Martin - I am getting errors when working with the current version of Ranger downloaded 7/27/2020.  

I am on a MAC platform, using the c++ Ranger version: 0.12.4, which I pulled and made today, checking to make sure that all software is the latest versions.

If I call it with this 

./ranger --verbose --file iris.txt --depvarname Species --treetype 1 --probability --impmeasure 3 --write --outprefix irismodel

there no problem;  however the following call

./ranger --verbose --file iris.txt --depvarname Species --treetype 1 --probability --predict irismodel.forest --write --outprefix irismodel

produces an error

Loading input file: iris.txt.
Error: Could not open input file. Too few columns in row 0. Are all values numeric? Ranger will EXIT now.

If I use earlier Ranger versions specifically  0.11.4, or any previous version, no error results

The input file which works with Ranger  0.11.4 but  does not work with Ranger 0.12.4 is attached

[iris.txt](https://github.com/imbs-hl/ranger/files/4985618/iris.txt)

as its so small I will put it in plain text below

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
5.7 4.4 1.5 0.4 1
5.4 3.9 1.3 0.4 1
5.1 3.5 1.4 0.3 1
5.7 3.8 1.7 0.3 1
5.1 3.8 1.5 0.3 1
5.1 3.5 1.4 0.2 1
4.8 3.4 1.9 0.2 1
6.7 3.1 4.7 1.5 2
6.3 2.3 4.4 1.3 2
6.9 3.1 4.9 1.5 2
6.3 2.8 5.1 1.5 3
6.1 2.6 5.6 1.4 3
6.7 2.5 5.8 1.8 3
7.2 3.6 6.1 2.5 3
6.5 3.2 5.1 2 3

### PR DESCRIPTION
**Pull request by ivmai**
* change cpp version to 0.12.4
* Don't load dependent variable name a second time, fix #538
* Fix memory mode initialization

### CODE REVIEW

**Comment by ivmai** [comment]
Could someone help with fails on CI?

**Comment by mnwright** [comment]
I think the CI only works for PRs to the master branch. I just switched from Travis to GH actions, maybe it works now (with the updates from master)?

**Comment by ivmai** [comment]
I don't have authority to restart the checks.
Anyway, cmake && make successful - I tested it locally.

**Comment by ivmai** [comment]
@mnwright, do you have any objections against merging this PR?

**Comment by mnwright** [comment]
No objections, I'll merge. I'm thinking how to keep such a branch in sync with the master without too much work... Any ideas?

**Pull request merged**
