### PR TITLE
OOB quantreg in C++

### PR DESCRIPTION
**Pull request by mnwright**
See #459 and #473.

### CODE REVIEW

**Comment by dplecko** [comment]
Dear Marvin,

First, thanks a lot for the swift response and the implementation. I think the version you currently propose looks great. Let me just quickly comment on the current algorithm and how our approach in #473 could make it even faster (and maybe substantially so). So in the proposed C++ code we have:

A. the first level of nesting over the trees
`  for (size_t i = 0; i < groups.ncol(); ++i) {
`
and the only thing that can be done about this is parallelization (as mentioned in #459)

B. the second level of nesting over the observations
`    for (size_t j = 0; j < groups.nrow(); ++j) {
`
which also has to be there.

C. the third level of nesting, which goes over all observations again.
`for (size_t k = 0; k < groups.nrow(); ++k) { 
`
It is the third level of nesting that is avoidable and this is where our speed improvement in #473  comes from. The algorithmic description would be the following:

Before the second level of nesting, we can have another for loop which goes through all the observations and groups them according to terminal node.

The difference then is that, once we reach part B., we already now terminal node membership. Therefore, the third nesting level in C. is not necessary any longer. In the line
`        
result(j, i) = y(Rcpp::sample(others, 1, false)[0]);
`

we sample an observation from the same terminal node (but from the terminal node which excludes the current observation). If you, as in our approach, have the information about the whole terminal node, you cannot guarantee that you will not get the current observation in the sampling. The nice thing about this is that, if you sample 2 things from the terminal node, one of them will certainly differ from the current observation and that one we can keep. It would be possible to check if the sample observation is actually the current one with a simple if statement.

Please let me know if my explanation is clear enough. I think it really does allow us to avoid a whole level of nesting.

Best,
Drago

**Comment by mnwright** [comment]
Thanks for checking the code. 

> Before the second level of nesting, we can have another for loop which goes through all the observations and groups them according to terminal node.

I was thinking the same but I couldn't come up with an efficient solution for the grouping. Any suggestions? PR very welcome! 

Btw., this version should already be faster than the one in #473, isn't it?

**Comment by dplecko** [comment]
> Thanks for checking the code.

No problem, thanks a lot for putting out this version.

> I was thinking the same but I couldn't come up with an efficient solution for the grouping. Any suggestions? PR very welcome!

Let me try to describe our algorithmic approach. I think the current version you have is not at all far from it, so in case you want to add this that would be great. If not, let me know and I'll go for a PR some time soon.

I am looking at a single tree now. Currently we have `O(n^2)` complexity (after ignoring the the nesting over trees). I think this can be made `O(n)` with slightly more memory or `O(n logn)` with the same memory usage as the current version.

1. `O(n)` solution
Let `groups(:, i)` be the vector which tells us about terminal node membership of the observations. In the first iteration over the whole vector `groups(:,i)` we can identify the unique terminal node values that appear and assign them numbers `1,..., n_T` (cost O(n)). Then, for each terminal node, we open a structure which is the same as the currently used `others` integer vector. We need such a structure for every terminal node, and it should include all the observations in the node. Adding all observations to corresponding terminal node vectors is also O(n). 

In the final iteration through observations, we sample 2 things from the terminal node vector of the current observation 

2. `O(n logn)` solution:
Would need to sort the sequence of observations `1,..., n` in such a way that the resulting sequence has the observations in the same terminal node in a consective order. More precisely, `i` should precede `j`  in the sorted sequence if `T(i) > T(j)`, where `T(i)` is the terminal node of observation `i`. This sort is of complexity O(n logn). After sorting in this way, we can apply the same procedure as in solution 1., but we can reuse the integer vector corresponding to `others`, because once we move past the current terminal node in this sequence, we don't have to look back.

> Btw., this version should already be faster than the one in #473, isn't it?

Yes, I agree. The additional algorithmic improvement from #473 will make it blazing fast though :-)

Let me know which option you prefer most. And thanks again!

Best,
Drago

**Comment by mnwright** [comment]
Thanks. Option 2 looks like a good solution and might even be faster because in option 1 the structure you describe would have to be re-created for every tree. 

PR welcome!

**Comment by mnwright** [comment]
Thanks, I've made some code style changes, added comments and merged with current master.

**Pull request merged**
