### PR TITLE
Refactor manual memory management

### PR DESCRIPTION
**Pull request by dancooke**
This branch makes several important changes. In summary:

- Replace all owned polymorphic pointer types with smart pointers (all `std::unique_ptr`).
- Replace all owned non-polymorphic pointer types with containers (all `std::vector`).
- Improve `const` correctness throughout (pointer and references).

In principle, this should eliminate all memory leaks (I spotted a few) as there is now no manually managed memory (i.e. no direct `new` calls). I also think this makes the code far easier to understand as it makes object ownership clear.

I've tested the stand-alone C++ version with Clangs sanitiser and found no issues, however, I haven't tested the R version, so it's possible this will need further changes (in particular `rangerCpp.cpp`).

### CODE REVIEW

**Comment by dancooke** [comment]
I'm not sure which tests are failing - I can't seem to find the appropriate log file.

**Comment by dancooke** [comment]
Just to clear up what impact these changes may have on the R version: since `DataDouble` now stores it's data in a `std::vector`, a copy of the input data `Rcpp::NumericMatrix` must be made. I'm not sure the current way of implicitly converting `NumericMatrix` to `double*` is safe anyway as I can't see any guarantee that `NumericMatrix` storage is contagious (although in practise it likely is). `std::vector` can be efficiently moved so only one copy is made here, and then the original `NumericMatrix` is destroyed. It's possible this operation will be optimised away anyway.

**Comment by mnwright** [comment]
I've tested this PR and the R package seems to run fine on Mac. On Windows there are still some problems (although AppVeyor succeeded). Runtimes also look OK. 

I'll add your changes one by one to check for possible problems (and to learn something).

**Comment by mnwright** [comment]
It's working now. We still have one problem: By using a `std::vector` for the data, we'll have to copy it in the R version, increasing memory usage drastically for large data sets.

**Comment by mnwright** [comment]
Added `DataRcpp` using `Rcpp::NumericMatrix` for data storage. 

Should be ready to merge now. Thanks again @dancooke!

**Comment by dancooke** [comment]
Great, once this is merged with master I'll try to address some of the other issues that I've raised.

**Comment by mnwright** [comment]
Merged.

**Pull request merged**
