### PR TITLE
Case-wise importances

### PR DESCRIPTION
**Pull request by rcannood**
First of all, thanks for creating ranger. Having looked at the source code of randomForest and randomForestSRC, working with/on ranger is absolute bliss in comparison. 

This PR adds the possibility of computing case-wise importance values to ranger (related to #273). 
I added implementations for classification, regression, probability and survival trees. I also added unit tests to make sure that the case-wise importance values produce expected results. When the case-wise importance values are not asked for, the effect on performance should be minimal. 

### Example
```r
library(tidyverse)

tib <- 
  tibble(
    x = runif(1000),
    y = rnorm(1000, mean = 1),
    z = rnorm(1000, mean = 2),
    a = ifelse(x < .5, y, z)
  ) %>% arrange(x)

rf <- ranger::ranger(
  data = tib,
  dependent.variable.name = "a",
  importance = "permutation",
  local.importance = TRUE,
  num.threads = 1
)
vic <- rf$variable.importance.casewise
# cut off the importance values to make the heatmap 
# easier to interpret
vic[vic > 1.5] <- 1.5
pheatmap::pheatmap(
  vic,
  cluster_cols = FALSE, 
  cluster_rows = FALSE,
  show_rownames = FALSE
)
```
plot_zoom_png

### Implementation details
In the current implementation, I added a [new ImportanceMode](https://github.com/imbs-hl/ranger/compare/master...rcannood:master#diff-fbbc564748ecd06c32f525a90464db8cR60): `IMP_PERM_CASEWISE`, though now I'm thinking it would have been better to pass it as a boolean variable to [Forest::initCpp](https://github.com/imbs-hl/ranger/blob/master/src/Forest.cpp#L66). This way, it would be possible to implement a casewise `IMP_PERM_BREIMAN` or even a casewise `IMP_GINI` (I have some ideas, not sure whether it will work). 
To choose whether case-specific feature importances need to be calculated, do you prefer using the ImportanceMode, or a simple boolean parameter?

Computing the actual case-specific values is relatively easy. I added one extra parameter to  [`computePredictionAccuracyInternal()`](https://github.com/imbs-hl/ranger/compare/master...rcannood:master#diff-4590db39cd4d123592404f481f3d9b96L111) such that if a pointer of a vector is passed along as an argument, the differences between the predicted value and the real value will be stored inside of the vector. Alternatively, a second function could be used specifically for this purpose, but this would lead to some redundant code. Which do you prefer?

Let me know which implementation changes you would like, and I will update the PR.

### List of changes

* Added encoding to DESCRIPTION, roxygen was complaining about it (89777d146047caaef65f2c5a0c460ea4f42ac62f)
* Removed library and require statements from examples, roxygen was complaining about it (6db513b3eecf03f0550d91c101e18b7e103c7ee5)
* Added casewise importances to ranger (2de61bf52a2676c53d0691ce1b7530b25c3fa10d) 
* Decided to transpose the output, in comparison to randomForest (72e8d3ad4af5124a624b7c07ffa0bcbe467beb14)
* Added a unit test to make sure that it works (e3057d68d868ee0df2abd76e4e8c7e603e0443b4)
* Added extra newline at the end of the DESCRIPTION (9d4e8d6)
* Implement casewise importances for survival trees (1cb9302)

### CODE REVIEW

**Comment by mnwright** [comment]
Thanks for the PR! I will try to check the details and merge soon.

**Comment by rcannood** [comment]
Alright, awesome! Let me know if you would like me to make certain changes to make this fit better with the existing codebase :)

**Comment by mnwright** [comment]
Sorry, I completely messed this up. 👎 Let's continue in #444. 

What happened: I cleaned up big already deleted files in our master with [bgf repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) and somehow your fork got 1163 commits ahead. 😳 
I think I recovered it in #444 and your contributions are still there.

**Comment by rcannood** [comment]
No worries! It's good that you removed the release files from the repository. Thanks for creating a new PR :)

**Pull request closed without merging**
