### PR TITLE
Case-wise importances 2

### PR DESCRIPTION
**Pull request by mnwright**
Continuing #439 here.

### CODE REVIEW

**Comment by mnwright** [comment]
OK, looks good. I renamed the output from `variable.importance.casewise` to `variable.importance.local` to match name with the `local.importance` argument. I also slightly changed the tests (they were quite slow) and added a pure C++ interface. 

The only thing I'm not sure yet is whether we should have the `local.importance` argument or add another importance mode to `importance`. I see your point in #439 that we might add local importance modes for the other modes. However, the list of arguments in ranger is already quite long...

**Comment by rcannood** [comment]
Sorry for the late reply! I had forgotten to subscribe to the new PR.

Thanks for taking a look at the code. 

I agree that there are already quite a lot of parameters, though this is just an inherent property of the random forests algorithm. I think adding an extra parameter would make more sense if the local importances get extended to other importance modes as well. Maybe we could consider changing the internals if or when this event occurs?

In ca2e4d0, I added a line of documentation regarding ranger output that I forgot to include, maybe you want to include this in the PR?

If all this is ok for you, feel free to merge at your earliest convenience :)

**Comment by rcannood** [comment]
Derp, sorry for the typo! 🙃

**Comment by rcannood** [comment]
I suppose this merge solves #273?

**Comment by mnwright** [comment]
Yes, thanks.

**Pull request merged**
