### PR TITLE
Regularization framework for regression and classification

### PR DESCRIPTION
**Pull request by brunaw**
Hey Marvin, 

This pull request adds the regularization framework for both regression and classification. A few details to take into consideration:

   - I deactivate the parallelization when doing regularization since I want the trees to globally "remember" which variables have already been used; 
  - I'm using the `all_split_varIDs` variable to check when a variable has already been used; 
  - I kept the use of the impurity importance when the regularization is done because that allows me to easily check how many and which variables have been used. If that's not very optimal we can think about something else. 

A basic example of how to use it is:

```
library(ranger)

not_regularized <- ranger(mpg ~ ., data = mtcars)
regularized <- ranger(mpg ~ .,
                      data = mtcars, 
                      mtry = 5, 
                      regularization = list(coef.reg = 0.1))

# Number of variables
sum(not_regularized$variable.importance > 0)
[1] 10

sum(regularized$variable.importance > 0)
[1] 7

# Errors
not_regularized$prediction.error
[1] 5.7743

regularized$prediction.error
[1] 5.5053
```

Thanks for all the help!

### CODE REVIEW

**Comment by mnwright** [comment]
@brunaw I'd like to make some changes but you created the PR from your master branch, which I don't have access rights to push to. Could you grant me access or create another PR from a branch?

**Comment by brunaw** [comment]
Hey @mnwright thank you so much!
 
I couldn't figure a way to grant you access to master, so I just put my commits into a branch called `pr-regularization`. Do you mind checking if the branch is correct and if I can ask for the merge from this branch now?  
https://github.com/regularization-rf/ranger/tree/pr-regularization

**Comment by mnwright** [comment]
Looks good. Just go ahead and create the PR.

**Comment by brunaw** [comment]
Thanks Marvin!

**Pull request closed without merging**
