### PR TITLE
Do not fiddle with compiler options to use pthreads

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by mnwright** [comment]
Thanks. That seems to be working on Linux. When I cross compile for Windows, I get "libgcc_s_seh-1.dll was not found" when running the executable. Not yet tried on a Mac.

**Comment by giordano** [comment]
> When I cross compile for Windows, I get "libgcc_s_seh-1.dll was not found" when running the executable.

Probably because you don't have mingw libraries in your PATH on Windows, but that seems to be tangential to this.

**Comment by mnwright** [comment]
>  but that seems to be orthogonal to this change.

No, it works fine without the change.

**Comment by giordano** [comment]
Because you're currently forcing `-static` for everyone, which isn't good. I don't want to do a static build for one, I have mingw libraries in place on windows. If you need to do a static build you can either set CFLAGS on the command line or add an option to do that, but inflicting it to everyone isn't useful.

**Comment by mnwright** [comment]
I see, that makes sense. Maybe we should move the `-static` part to the cross compile scripts and best create both static and dynamic linking versions when cross compiling.

**Comment by mnwright** [comment]
Thanks, included this in #684. Will also continue the cross compiling issue there.

**Pull request closed without merging**
