### PR TITLE
ranger, bootstrap for time series

### PR DESCRIPTION
**Pull request by hyanworkspace**
joint work with Benjamin Goehry

### CODE REVIEW

**Comment by mnwright** [comment]
Thanks for the PR! Do you have any examples or tests? 

Also, I wonder what is the best approach to include this. I see 3 options (feel free to propose another):
1. Merge into ranger as it is
2. Create an additional R function (e.g. `rangerts`) in the package
3. Fork the repo and have an additional package for time series 

The problem with 1. is that the number of arguments in `ranger()` grows and the interface as well as the code might be confusing. It might also be harder to add additional time series related stuff. With option 2. we keep the interface cleaner but not the C++ code (maybe that is also confusing). With option 3. we would have an additional repo to maintain but it would also be cleaner to separate the time series code. 

What are your thoughts on this?

**Comment by hyanworkspace** [comment]
Thanks for your message! We have discussed internally, and we think option 1 might be the best. In fact, our modifications focus only on the bootstrap step when building trees, and computing variable importance by permutation. The arguments we added can be hidden quite well, and most of time, they are inactive. 
Maybe I can push some testthat module for time series part, will do it very soon!

**Comment by Shafi2016** [comment]
Hello, Is bootstrap for time series implemented with a ranger now? Is there any example?

**Comment by hyanworkspace** [comment]
Hi the package rangerts is available here: https://github.com/hyanworkspace/rangerts.
We are waiting (if still possible) to be merged into the ranger package but you can test it out.

**Comment by Shafi2016** [comment]
Thank you so much!!!

**Comment by Shafi2016** [comment]
Hello @hyanworkspace, Have you thought of adding rangerts to modeltime (https://business-science.github.io/modeltime/articles/extending-modeltime.html)

**Comment by athammad** [comment]
Hi guys,

 I am jumping on this since I am very interested in `rangerts`. I would like to know if there is any chance to use the options of `rangerts` directly within `caret`. I have tried to run the following example but I don't think there is any impact on the results. 
```
rangerTS<-train(y=Y,x=X,
                   trControl = train_control,
                   tuneLength = 20,
                   method = 'ranger',
                   quantreg=TRUE, bootstrap.ts = "moving", block.size = 7)
```

**Comment by mnwright** [comment]
Sorry for the long silence. In addition to the lack of time to deal with this, I'm still not happy with adding four additional parameters to `ranger()` (which might also be confusing to users not using time series). 

We could also leave it as it is now (separate repo). Actually, you have quite some information on your repo, and now you get the credit for the package. 

Btw., we should create a lists if forks/extensions that build on ranger and link to them here in the repo.

**Comment by mnwright** [comment]
I think we leave it with the separate package.

See #724 for linking to repo.

**Pull request closed without merging**
